### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by operator-name** [rajpar29/termux-launcher#1]
I've been wanting to hack around with something like this but I've been a little wary of the other build since it's unlicensed. Any chance you're willing to release your code under an open source license?

https://choosealicense.com/

**Comment by rajpar29** [comment]
> I've been wanting to hack around with something like this but I've been a little wary of the other build since it's unlicensed. Any chance you're willing to release your code under an open source license?
> 
> https://choosealicense.com/

I will add the licence by tomorrow.

**Comment by rajpar29** [comment]
License added
