### ISSUE TITLE
bash completion files?

### ISSUE THREAD

**Issue by sudomain** [rajpar29/termux-launcher#3]
Hi, it seems I'm a couple years late to the party. Do you have the completion files or related config files mentioned on reddit?

**Comment by rajpar29** [comment]
Everything is committed.
I think you are talking about the `open` script. That is also there.


I have been thinking of creating a new version for this for a while.

**Comment by sudomain** [comment]
Sorry for that. I didn't think it was in the root directory and spent too long looking in subdirectories (I could've also used GH search, oops).

I'm hoping to use this as a component in an audio-based menu system. I don't have a repo up yet, but essentially it'll allow using features of your device using sequences of presses on the device volume keys as input, and audio as output. I was going to use `am` to launch apps, but I see your launcher already does that. Guess I don't need to reinvent the wheel 😁.

Any thoughts on a Python bindings/wrapper for your launcher?
